-- ============================================================
-- BÚSSOLA — lado do negócio: empresas, anúncios e destaques
--
-- Modelo: registar empresa e publicar anúncios é gratuito e sem
-- limite. O único ponto de cobrança é o destaque de um anúncio,
-- por período, com pagamento único e sem renovação automática.
-- ============================================================

-- ---------- Empresas ----------
create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null check (category in (
    'Advogados','Imobiliárias','Eventos','Empregos','Serviços',
    'Formação','Associações','Contabilidade','Saúde','Outra')),
  city text,
  nif text,
  email text,
  phone text,
  about text,
  -- estado de verificação, espelha a fila do painel de admin
  verification text not null default 'pending'
    check (verification in ('pending','review','verified','rejected','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.companies is 'Contas de empresa. O registo é gratuito: não existe subscrição.';

-- Quem pode gerir cada empresa. Tabela própria para permitir mais
-- do que um gestor (uma imobiliária tem vários agentes).
create table if not exists public.company_members (
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','manager')),
  created_at timestamptz not null default now(),
  primary key (company_id, user_id)
);

-- ---------- Anúncios ----------
-- Tabela única para vagas, imóveis, eventos e serviços: o destaque
-- aplica-se da mesma forma a todos, e assim a chave estrangeira do
-- destaque é simples em vez de polimórfica.
create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  kind text not null check (kind in ('job','home','event','service')),
  title text not null,
  city text,
  price_cents int check (price_cents is null or price_cents >= 0),
  details jsonb not null default '{}'::jsonb,   -- campos próprios de cada tipo
  status text not null default 'draft'
    check (status in ('draft','review','published','paused','removed')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.listings is 'Anúncios. Publicar é gratuito e sem limite de quantidade.';

-- ---------- Pacotes de destaque ----------
-- Em tabela, para o admin poder mudar preços sem novo deploy.
create table if not exists public.boost_packages (
  id text primary key,                    -- d7 | d15 | d30
  name text not null,
  days int not null check (days > 0),
  price_cents int not null check (price_cents >= 0),
  description text,
  active boolean not null default true,
  sort int not null default 0
);
comment on table public.boost_packages is 'Catálogo de destaques. Valores em cêntimos, nunca em vírgula flutuante.';

insert into public.boost_packages (id,name,days,price_cents,description,sort) values
  ('d7','7 dias',7,900,'Aparece no topo dos resultados durante uma semana.',1),
  ('d15','15 dias',15,1500,'O período com melhor relação entre custo e alcance.',2),
  ('d30','30 dias',30,2500,'Presença contínua durante um mês inteiro.',3)
on conflict (id) do nothing;

-- ---------- Destaques comprados ----------
create table if not exists public.boosts (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  package_id text not null references public.boost_packages(id),
  days int not null check (days > 0),
  price_cents int not null check (price_cents >= 0),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  status text not null default 'active'
    check (status in ('active','expired','refunded','cancelled')),
  receipt_no bigint generated by default as identity,  -- numeração sempre crescente
  payment_ref text,                                     -- referência do fornecedor de pagamento
  created_at timestamptz not null default now(),
  constraint periodo_valido check (ends_at > starts_at)
);
comment on table public.boosts is
  'Compras de destaque. Pagamento único: não há renovação automática.';
comment on column public.boosts.receipt_no is
  'Número de recibo. Identity garante que cresce sempre, mesmo com inserções concorrentes.';

create index if not exists idx_listings_company on public.listings(company_id);
create index if not exists idx_listings_publicos on public.listings(kind, city) where status = 'published';
create index if not exists idx_boosts_listing on public.boosts(listing_id, ends_at desc);
create index if not exists idx_boosts_ativos on public.boosts(ends_at) where status = 'active';
create index if not exists idx_members_user on public.company_members(user_id);
